name: Compile SRS Ruleset

on:
  push:
    paths:
      - '**/*.json'

jobs:
  compile-srs:
    runs-on: ubuntu-latest

    env:
      SING_BOX_VERSION: "1.11.0"  # 请根据需要设置版本号

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download sing-box
      run: |
        curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION}-linux-amd64.tar.gz
        tar -xzf sing-box.tar.gz
        chmod +x sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box
        sudo mv sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box /usr/local/bin/sing-box

    - name: Find and compile JSON files
      run: |
        for file in $(find . -type f -name "*.json"); do
          sing-box rule-set compile --output "${file%.json}.srs" "$file"
        done
