name: Compile and Push SRS Ruleset

on:
  push:
    paths:
      - '**/*.json'
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  compile-and-push-srs:
    runs-on: ubuntu-latest

    env:
      SING_BOX_VERSION: "1.11.6"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Download sing-box
      run: |
        curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION}-linux-amd64.tar.gz
        tar -xzf sing-box.tar.gz
        chmod +x sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box
        sudo mv sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box /usr/local/bin/sing-box

    - name: remove srs
      run: |
        find . -type f -name "*.srs" -exec rm -f {} \;

    - name: Find and compile JSON files
      run: |
        for file in $(find . -type f -name "*.json"); do
          sing-box rule-set compile --output "${file%.json}.srs" "$file"
        done

    - name: Commit and push compiled SRS files
      run: |
        git add *.srs
        git commit -m 'Compile and add SRS rulesets'
        git push
