# This is a basic workflow to help you get started with Actions

name: compile srs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download and unzip `sing-box` core-0.10.3
        run: |
          wget https://github.com/SagerNet/sing-box/releases/download/v1.10.3/sing-box-1.10.3-linux-amd64.tar.gz -O - | tar -zxf - -C ./tools/
          mv -f ./tools/sing-box-1.10.3-linux-amd64/sing-box ./tools/sing-box
      
      - name: Generate `sing-box` rule_set
        run: |
          mkdir -p ./sing-box-ruleset/
          cd ./tools/
          sed -i 's/"version": 1/"version": 2/' ./convert.sh
          chmod +x ./convert.sh && ./convert.sh
          rm -rf ./sing-box* ./rules*
          mv -f ./*.json ./*.srs ../sing-box-ruleset/
      

          

