name: Compile Sing-Box Rules

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
        - name: Download and unzip `sing-box` core
          run: |
           wget https://github.com/DustinWin/clash_singbox-tools/releases/download/sing-box/sing-box-release-linux-amd64.tar.gz -O - | tar -zxf - -C ./tools/
           mv -f ./tools/CrashCore ./tools/sing-box

        - name: Generate `sing-box` rule_set
          run: |
           mkdir -p ./sing-box-ruleset/
           cd ./tools/
           sed -i 's/"version": 1/"version": 2/' ./convert.sh
           chmod +x ./convert.sh && ./convert.sh
           rm -rf ./sing-box* ./rules*
           mv -f ./*.json ./*.srs ../sing-box-ruleset/
